name: Create cache on cachix

on:
  push:
    branches: [master]

env:
  NIXPKGS_ALLOW_UNFREE: 1

jobs:
  cache:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v10
        with:
          name: aiotter
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      # Home manager
      - run: nix build .#home.switch --impure
      - run: nix build .#home.home-manager

      # Nix-Darwin
      - run: nix build .#darwin.system .#darwin.switch
        if: matrix.os == 'macos-latest'
