name: Create cache on cachix

on:
  push:
    branches: [darwin]

env:
  NIXPKGS_ALLOW_UNFREE: 1

jobs:
  check:
    uses: aiotter/systems/.github/workflows/check.yml@master

  cache:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        target:
          - .#switch
          - .#darwin-system
    uses: aiotter/systems/.github/workflows/cache.yml@master
    with:
      runs_on: ${{ matrix.os }}
      target: ${{ matrix.target }}
