name: Create cache on cachix

on:
  push:
    branches: [darwin]

env:
  NIXPKGS_ALLOW_UNFREE: 1

jobs:
  cache:
    uses: aiotter/systems/.github/workflows/cache.yml@master
    with:
      targets: .#switch .#darwin-system
    secrets:
      cachix-auth-token: ${{ secrets.CAHIX_AUTH_TOKEN }}
