name: Create cache on cachix

on:
  push:
    branches: [master]

env:
  NIXPKGS_ALLOW_UNFREE: 1

jobs:
  cache:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - build: .#home.switch
            impure: true
          - build: .#home.home-manager
            impure: false
          - build: .#darwin.system
            impure: false
          - build: .#darwin.switch
            impure: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v10
        with:
          name: aiotter
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix build ${{ matrix.build }} ${{ matrix.impure && '--impure' || '' }}
        id: build
      - run: nix log ${{ matrix.build }} ${{ matrix.impure && '--impure' || '' }}
        if: ${{ failure() && steps.build.conclusion == 'failure' }}
