name: Create cache on cachix

on:
  push:
    branches: [home]

env:
  NIXPKGS_ALLOW_UNFREE: 1

jobs:
  # https://github.com/NixOS/nix/issues/4265
  # check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2.4.0
  #     - uses: cachix/install-nix-action@v17
  #       with:
  #         nix_path: nixpkgs=channel:nixos-unstable
  #         extra_nix_config: |
  #           access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
  #     - run: nix flake check --impure

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        build:
          - .#home-manager
          - .#homeConfigurations.$(nix eval --expr builtins.currentSystem --impure).default.activationPackage
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v11
        with:
          name: aiotter
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix build ${{ matrix.build }} ${{ matrix.impure && '--impure' || '' }}
        id: build
      - run: nix log ${{ matrix.build }} ${{ matrix.impure && '--impure' || '' }}
        if: ${{ failure() && steps.build.conclusion == 'failure' }}
