name: Build flake outputs and cache binaries on cachix

on:
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
      target:
        required: true
        type: string

env:
  NIXPKGS_ALLOW_UNFREE: 1

jobs:
  cache:
    runs-on: ${{ inputs.runs_on }}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v11
        with:
          name: aiotter
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix build ${{ inputs.target }}
        id: build
      - run: nix log ${{ inputs.target }}
        if: ${{ failure() && steps.build.conclusion == 'failure' }}
