name: Create cache on cachix

on:
  push:
    branches: [home]

env:
  NIXPKGS_ALLOW_UNFREE: 1

jobs:
  cache:
    uses: aiotter/systems/.github/workflows/cache.yml@master
    with:
      targets: .#home-manager .#homeConfigurations.$(nix eval --expr builtins.currentSystem --impure).default.activationPackage
    secrets:
      cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
